"""agregar columna estado a tareas

Revision ID: 40cd5a06ae96
Revises: 64f96fc82be5
Create Date: 2025-04-04 17:14:22.421631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40cd5a06ae96'
down_revision: Union[str, None] = '64f96fc82be5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tareas', sa.Column('estado', sa.String(length=20), nullable=True))
    op.add_column('tareas', sa.Column('prioridad', sa.String(length=10), nullable=True))
    op.add_column('tareas', sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
    op.add_column('tareas', sa.Column('fecha_limite', sa.DateTime(), nullable=True))
    op.alter_column('tareas', 'descripcion',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('tareas', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_tareas_titulo', table_name='tareas')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tareas_titulo', 'tareas', ['titulo'], unique=False)
    op.alter_column('tareas', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tareas', 'descripcion',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('tareas', 'fecha_limite')
    op.drop_column('tareas', 'fecha_creacion')
    op.drop_column('tareas', 'prioridad')
    op.drop_column('tareas', 'estado')
    # ### end Alembic commands ###
